// <auto-generated />
using System;
using FinanceSplit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceSplit.Data.Migrations
{
    [DbContext(typeof(FinanceSplitDbContext))]
    partial class FinanceSplitDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LatestMigrationId => "20260501111416_InitialCreate";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.3.26207.106");

            modelBuilder.Entity("FinanceSplit.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FinanceSplit.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaidById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaidById");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TransactionParticipants", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionParticipants");
                });

            modelBuilder.Entity("FinanceSplit.Domain.Entities.Person", b =>
                {
                    b.OwnsMany("FinanceSplit.Domain.ValueObjects.Salary", "_salaries", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.HasKey("PersonId", "Id");

                            b1.ToTable("Salaries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("_salaries");
                });

            modelBuilder.Entity("FinanceSplit.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinanceSplit.Domain.Entities.Person", "PaidBy")
                        .WithMany()
                        .HasForeignKey("PaidById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FinanceSplit.Domain.ValueObjects.Recurrence", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("StartMonth")
                                .HasColumnType("TEXT")
                                .HasColumnName("RecurrenceStartMonth");

                            b1.Property<int?>("TerminationCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RecurrenceTerminationCount");

                            b1.Property<DateOnly?>("TerminationEndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("RecurrenceTerminationEndDate");

                            b1.Property<string>("TerminationType")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("RecurrenceTerminationType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("FinanceSplit.Domain.ValueObjects.SplitPay", "SplitPay", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SplitType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("SplitType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("PaidBy");

                    b.Navigation("Recurrence");

                    b.Navigation("SplitPay")
                        .IsRequired();
                });

            modelBuilder.Entity("TransactionParticipants", b =>
                {
                    b.HasOne("FinanceSplit.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceSplit.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
